[build-system]
requires = ["setuptools>=46.1.0", "wheel", "setuptools_scm[toml]>=5"]
build-backend = "setuptools.build_meta"

[tool]
[tool.setuptools_scm]
version_scheme = "no-guess-dev"
local_scheme = "no-local-version"
